FROM mcr.microsoft.com/dotnet/core/runtime:3.1 AS base

RUN apt-get update && \
    apt-get install -y --no-install-recommends unzip procps && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash moduleuser
USER moduleuser
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg

FROM base
WORKDIR /app
COPY ./out ./

ENTRYPOINT ["dotnet", "starter.dll"]
